### ISSUE TITLE
Update issue => minimise app instead of close

### ISSUE THREAD

**Issue by LiloBzH** [keeweb/keeweb#1757]
Since 2 or 3 versions, "minimise app instead of close" has broken update system

Where new file is ready, updater sytem want to close app (to update) but app is minimised ^^ so no update ^^

If i disable option MINIMIZE THE APP INSTEAD OF CLOSE, update work !

OS : Windows 10 pro

**Comment by antelle** [comment]
Hi! This is fixed in v1.17.4, updating from this version should work as expexted

**Comment by LiloBzH** [comment]
ah !! 

sorry for this ticket. Thank's for update ! :)

**Comment by LiloBzH** [comment]
@antelle Hi. For me, it's not fixed

Update 1.17.5 to 1.17.6 => same problem.

When a click to RESTART TO UPDATE => app is minimised.

I can force upgrade => i close the app

**Comment by antelle** [comment]
Thanks, I'll check it, maybe it was not fixed completely
