### ISSUE TITLE
Drag & drop throws js errors

### ISSUE THREAD

**Issue by apollo13** [keeweb/keeweb#363]
I am on the latest version from gh-pages, drag and drop results in errors like these:
![selection_494](https://cloud.githubusercontent.com/assets/81547/18448127/11dfaaba-792a-11e6-9a9a-f9c86a2ea6a8.png)
This happens on Firefox 49.01b1 -- anything I can do to debug?

**Comment by antelle** [comment]
Hello! It's working ok for me.
Please add more details.
- what were your actions?
- does it happen on Demo or New database?
- your operating system

**Comment by apollo13** [comment]
* It happens on the webversion https://app.keeweb.info/ (as well as locally) on any DB.
 * I am trying to drag an entry into another group, as soon as I hit a group I get b.indexOf is not a function
 * System is debian unstable, though I think this will be mostly browser related

I also tried locally with the develop branch, same there. Is there any way I can bust the app-cache manifest and ensure that I have the newest version? I remember that updating the app-cache was not always the easiest task…

**Comment by antelle** [comment]
> drag an entry into another group

Thanks, the same for me, now it's clear, will be fixed.

**Comment by antelle** [comment]
Deployed to [beta.keeweb.info](https://beta.keeweb.info), will be available in the next release

**Comment by apollo13** [comment]
Confirmed that it works :+1: Thanks! Couldn't get it to work locally though, somehow app-cache hates me.

**Comment by antelle** [comment]
It's fixed in release-1.3 branch, are you on it? If you are running locally with `grunt dev`, there's no app cache.

**Comment by apollo13** [comment]
jupp, I ran _grunt dev_ and then _firefox tmp/index.html_ -- still broken, odd…

**Comment by antelle** [comment]
Very strange... Did you pull the fix? You can view the source in Firefox, we have sourcemaps support. Most probably there are some troubles with git repo.

**Comment by apollo13** [comment]
Oh, I just ran `grunt dev` and didn't run `grunt` to regenerate the files in `tmp` -- sorry.

**Comment by antelle** [comment]
I got it, I'll change dev task, so that it will run necessary tasks first and then start a web server. There also should be another task, for just fast starting a server.

**Comment by apollo13** [comment]
Perfect, I just deployed the fixed file to my server, now I just have to figure out how to bust the app-cache :D

**Comment by antelle** [comment]
Just modify `manifest.appcache` file in any way, the app will see this and show update bell.

**Comment by apollo13** [comment]
Ah, that it was -- thank you, now everything works flawless.

**Comment by antelle** [comment]
Let's keep it open, until it's deployed

**Comment by apollo13** [comment]
Sorry

**Comment by antelle** [comment]
Now we have separate `grunt dev` and `grunt devsrv` tasks: `dev` will build everything it need and start the dev-server.
